=== barnabyg/tsa/src/main/resources/strategy.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

<xs:complexType name="tradetype">
 <xs:all>
  <xs:element name="instrument" type="xs:string"/>
  <xs:element name="type" type="xs:string"/>
  <xs:element name="quantity" type="xs:int" minOccurs="0"/>
 </xs:all>
</xs:complexType>

<xs:element name="rules">
  <xs:complexType>
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="indicator-direction-rule" maxOccurs="unbounded">
        <xs:complexType>
          <xs:all>
           <xs:element name="indicator">
            <xs:complexType>
             <xs:all>
              <xs:element name="name" type="xs:string"/>
              <xs:element name="operation" type="xs:string"/>
             </xs:all>
            </xs:complexType>
           </xs:element>
            <xs:element name="trade" type="tradetype"/>
          </xs:all>
        </xs:complexType>
      </xs:element>
      <xs:element name="indicator-value-rule" maxOccurs="unbounded">
        <xs:complexType>
          <xs:all>
           <xs:element name="indicator">
            <xs:complexType>
             <xs:all>
              <xs:element name="name" type="xs:string"/>
              <xs:element name="operation" type="xs:string"/>
              <xs:element name="value" type="xs:float"/>
             </xs:all>
            </xs:complexType>
           </xs:element>
            <xs:element name="trade" type="tradetype"/>
          </xs:all>
        </xs:complexType>
      </xs:element>
    </xs:choice>
  </xs:complexType>
</xs:element>

</xs:schema>

=== barnabyg/tsa/src/test/resources/rising-strategy.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<rules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="strategy.xsd">
 <indicator-direction-rule>
  <indicator>
   <name>FIVE_DAY_AVERAGE_DIRECTION</name>
   <operation>RISING</operation>
  </indicator>
  <trade>
   <instrument>BP.L</instrument>
   <type>BUY</type>
   <quantity>1</quantity>
  </trade>
 </indicator-direction-rule>
</rules>

=== barnabyg/tsa/src/test/resources/test-strategy.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<rules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="strategy.xsd">
 <indicator-direction-rule>
  <indicator>
   <name>FIVE_DAY_AVERAGE_DIRECTION</name>
   <operation>RISING</operation>
  </indicator>
  <trade>
   <instrument>BP.L</instrument>
   <type>BUY</type>
   <quantity>1</quantity>
  </trade>
 </indicator-direction-rule>
 <indicator-direction-rule>
  <indicator>
   <name>FIVE_DAY_AVERAGE_DIRECTION</name>
   <operation>FALLING</operation>
  </indicator>
  <trade>
   <instrument>BP.L</instrument>
   <type>SELL</type>
   <quantity>1</quantity>
  </trade>
 </indicator-direction-rule>
 <indicator-direction-rule>
  <indicator>
   <name>THIRTY_DAY_AVERAGE_DIRECTION</name>
   <operation>RISING</operation>
  </indicator>
  <trade>
   <instrument>BP.L</instrument>
   <type>BUY</type>
   <quantity>1</quantity>
  </trade>
 </indicator-direction-rule>
 <indicator-direction-rule>
  <indicator>
   <name>FIVE_DAY_VOLATILITY_DIRECTION</name>
   <operation>RISING</operation>
  </indicator>
  <trade>
   <instrument>BP.L</instrument>
   <type>BUY</type>
   <quantity>5</quantity>
  </trade>
 </indicator-direction-rule>
 <indicator-value-rule>
  <indicator>
   <name>FIVE_DAY_AVERAGE</name>
   <operation>GREATER</operation>
   <value>500</value>
  </indicator>
  <trade>
   <instrument>BP.L</instrument>
   <type>SELLALL</type>
  </trade>
 </indicator-value-rule>
</rules>
